import React, { useState, useEffect } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { generateEmailService, sendEmailService } from "../services/emailService";
import { getTargetService } from "../../targets/services/targetService";
import toast from "react-hot-toast";

const ComposeEmailPage = () => {
  const { targetId } = useParams();
  const navigate = useNavigate();
  const [target, setTarget] = useState(null);
  const [subject, setSubject] = useState("");
  const [body, setBody] = useState("");
  const [senderName, setSenderName] = useState("");
  const [senderEmail, setSenderEmail] = useState("");
  const [generating, setGenerating] = useState(false);
  const [sending, setSending] = useState(false);

  useEffect(() => {
    const fetchTarget = async () => {
      try {
        const { data } = await getTargetService(targetId);
        setTarget(data);
      } catch {
        toast.error("Target not found");
        navigate("/targets");
      }
    };
    fetchTarget();
  }, [targetId, navigate]);

 const handleGenerate = async () => {
    setGenerating(true);
    try {
      const { data } = await generateEmailService(targetId);
      setSubject(data.subject);
      setBody(data.body);
      toast.success("Email generated by AI!");
    } catch (err) {
      toast.error(err.response?.data?.message || "Generation failed");
    } finally {
      setGenerating(false);
    }
  };
  const handleSend = async () => {
    if (!subject || !body) return toast.error("Generate or write an email first!");
    if (!senderName || !senderEmail) return toast.error("Sender name aur email baro!");
    setSending(true);
    try {
      await sendEmailService({ targetId, subject, body, senderName, senderEmail });
      toast.success("Email sent successfully!");
      navigate("/campaigns");
    } catch (err) {
      toast.error(err.response?.data?.message || "Send failed");
    } finally {
      setSending(false);
    }
  };

  return (
    <div style={styles.container}>
      <div style={styles.card}>
        <h2 style={styles.title}>📧 Compose Phishing Email</h2>

        {target && (
          <div style={styles.targetInfo}>
            <span style={styles.badge}>Target: {target.name} — {target.email} ({target.company})</span>
          </div>
        )}

        <button style={styles.aiBtn} onClick={handleGenerate} disabled={generating}>
          {generating ? "⏳ Generating..." : "🤖 Generate with AI"}
        </button>

        {/* Sender Fields */}
        <input
          style={styles.input}
          type="text"
          placeholder="Sender Name (e.g. Sarah Johnson - HR Manager)"
          value={senderName}
          onChange={(e) => setSenderName(e.target.value)}
        />
        <input
          style={styles.input}
          type="text"
          placeholder="Sender Email (e.g. hr@deloitte.com)"
          value={senderEmail}
          onChange={(e) => setSenderEmail(e.target.value)}
        />

        <input
          style={styles.input}
          type="text"
          placeholder="Subject"
          value={subject}
          onChange={(e) => setSubject(e.target.value)}
        />

        <textarea
          style={styles.textarea}
          placeholder="Email body (HTML supported). Use {{TRACKING_LINK}} for clickable link tracking."
          value={body}
          onChange={(e) => setBody(e.target.value)}
        />

        {body && (
          <div style={styles.preview}>
            <p style={styles.previewLabel}>📄 Preview:</p>
            <div dangerouslySetInnerHTML={{ __html: body }} style={styles.previewContent} />
          </div>
        )}

        <div style={styles.btnRow}>
          <button style={styles.cancelBtn} onClick={() => navigate("/targets")}>Cancel</button>
          <button style={styles.sendBtn} onClick={handleSend} disabled={sending}>
            {sending ? "Sending..." : "📤 Send Email"}
          </button>
        </div>
      </div>
    </div>
  );
};

const styles = {
  container: { padding: "2rem", background: "#0f172a", minHeight: "100vh", display: "flex", justifyContent: "center" },
  card: { background: "#1e293b", padding: "2rem", borderRadius: "12px", width: "100%", maxWidth: "700px", height: "fit-content" },
  title: { color: "#f1f5f9", marginBottom: "1rem" },
  targetInfo: { marginBottom: "1rem" },
  badge: { background: "#0f172a", color: "#94a3b8", padding: "0.4rem 0.8rem", borderRadius: "6px", fontSize: "0.85rem" },
  aiBtn: { width: "100%", padding: "0.75rem", background: "#8b5cf6", color: "#fff", border: "none", borderRadius: "8px", cursor: "pointer", fontSize: "1rem", marginBottom: "1rem" },
  input: { width: "100%", padding: "0.75rem", marginBottom: "1rem", borderRadius: "8px", border: "1px solid #334155", background: "#0f172a", color: "#f1f5f9", fontSize: "1rem", boxSizing: "border-box" },
  textarea: { width: "100%", padding: "0.75rem", height: "180px", marginBottom: "1rem", borderRadius: "8px", border: "1px solid #334155", background: "#0f172a", color: "#f1f5f9", fontSize: "0.9rem", resize: "vertical", boxSizing: "border-box" },
  preview: { background: "#0f172a", borderRadius: "8px", padding: "1rem", marginBottom: "1rem" },
  previewLabel: { color: "#94a3b8", fontSize: "0.85rem", marginBottom: "0.5rem" },
  previewContent: { color: "#f1f5f9", fontSize: "0.9rem" },
  btnRow: { display: "flex", gap: "1rem" },
  cancelBtn: { flex: 1, padding: "0.75rem", background: "#334155", color: "#f1f5f9", border: "none", borderRadius: "8px", cursor: "pointer" },
  sendBtn: { flex: 1, padding: "0.75rem", background: "#10b981", color: "#fff", border: "none", borderRadius: "8px", cursor: "pointer" },
};

export default ComposeEmailPage;