import React, { useState, useEffect } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { generateEmailService, sendEmailService } from "../services/emailService";
import { getTargetService } from "../../targets/services/targetService";
import toast from "react-hot-toast";

const SENDER_PRESETS = [
  { label: "HR Department", name: "HR Department", email: "hr@company.com" },
  { label: "IT Support", name: "IT Support", email: "support@itsupport.com" },
  { label: "Google Security", name: "Google Security", email: "no-reply@google.com" },
  { label: "Accounts Payable", name: "Accounts Payable", email: "accounts@finance.com" },
  { label: "CEO Office", name: "CEO Office", email: "ceo@company.com" },
  { label: "Amazon", name: "Amazon", email: "no-reply@amazon.com" },
  { label: "Custom...", name: "", email: "" },
];

const ComposeEmailPage = () => {
  const { targetId } = useParams();
  const navigate = useNavigate();
  const [target, setTarget] = useState(null);
  const [subject, setSubject] = useState("");
  const [body, setBody] = useState("");
  const [replyToEmail, setReplyToEmail] = useState("");
  const [showAsName, setShowAsName] = useState("HR Department");
  const [showAsEmail, setShowAsEmail] = useState("hr@company.com");
  const [selectedPreset, setSelectedPreset] = useState(0);
  const [generating, setGenerating] = useState(false);
  const [sending, setSending] = useState(false);

  useEffect(() => {
    const fetchTarget = async () => {
      try {
        const { data } = await getTargetService(targetId);
        setTarget(data);
      } catch {
        toast.error("Target not found");
        navigate("/targets");
      }
    };
    fetchTarget();
  }, [targetId, navigate]);

  const handlePreset = (index) => {
    setSelectedPreset(index);
    const p = SENDER_PRESETS[index];
    if (p.label !== "Custom...") {
      setShowAsName(p.name);
      setShowAsEmail(p.email);
    } else {
      setShowAsName("");
      setShowAsEmail("");
    }
  };

  const handleGenerate = async () => {
    setGenerating(true);
    try {
      const { data } = await generateEmailService(targetId);
      setSubject(data.subject);
      setBody(data.body);
      toast.success("Email generated by AI!");
    } catch (err) {
      toast.error(err.response?.data?.message || "Generation failed");
    } finally {
      setGenerating(false);
    }
  };

  const handleSend = async () => {
    if (!subject || !body) return toast.error("Subject and body are required!");
    if (!replyToEmail.trim()) return toast.error("Reply-To email is required!");
    if (!showAsName.trim()) return toast.error("Display name is required!");
    if (!showAsEmail.trim()) return toast.error("Display email is required!");
    setSending(true);
    try {
      await sendEmailService({ targetId, subject, body, replyToEmail, showAsName, showAsEmail });
      toast.success(`Email sent as "${showAsName}"!`);
      navigate("/campaigns");
    } catch (err) {
      toast.error(err.response?.data?.message || "Send failed");
    } finally {
      setSending(false);
    }
  };

  return (
    <div style={styles.container}>
      <div style={styles.card}>
        <h2 style={styles.title}>📧 Compose Phishing Email</h2>

        {target && (
          <div style={styles.targetInfo}>
            <span style={styles.badge}>🎯 Target: {target.name} — {target.email} ({target.company})</span>
          </div>
        )}

        {/* Section 1 — Reply To */}
        <div style={styles.section}>
          <div style={styles.sectionTitle}>↩️ Reply-To Email (replies from receiver will come here)</div>
          <input
            style={styles.input}
            type="email"
            placeholder="e.g. your@gmail.com"
            value={replyToEmail}
            onChange={(e) => setReplyToEmail(e.target.value)}
          />
        </div>

        {/* Section 2 — Show As */}
        <div style={styles.section}>
          <div style={styles.sectionTitle}>🎭 Show As (receiver will see this in "From")</div>
          <div style={styles.presetRow}>
            {SENDER_PRESETS.map((p, i) => (
              <button
                key={i}
                style={{ ...styles.presetBtn, ...(selectedPreset === i ? styles.presetBtnActive : {}) }}
                onClick={() => handlePreset(i)}
              >
                {p.label}
              </button>
            ))}
          </div>
          <div style={styles.showAsRow}>
            <input
              style={{ ...styles.input, flex: 1, marginBottom: 0 }}
              type="text"
              placeholder="Display Name — e.g. HR Department"
              value={showAsName}
              onChange={(e) => setShowAsName(e.target.value)}
            />
            <input
              style={{ ...styles.input, flex: 1, marginBottom: 0 }}
              type="text"
              placeholder="Fake Email — e.g. hr@amazon.com"
              value={showAsEmail}
              onChange={(e) => setShowAsEmail(e.target.value)}
            />
          </div>

          {/* Preview */}
          <div style={styles.previewBox}>
            <div style={styles.previewRow}>
              <span style={styles.previewLabel}>From:</span>
              <span style={styles.previewVal}>"{showAsName}" &lt;{showAsEmail}&gt;</span>
            </div>
            <div style={styles.previewRow}>
              <span style={styles.previewLabel}>Reply-To:</span>
              <span style={{ ...styles.previewVal, color: "#f59e0b" }}>{replyToEmail || "—"}</span>
            </div>
            <div style={styles.previewRow}>
              <span style={styles.previewLabel}>Actual Send:</span>
              <span style={{ ...styles.previewVal, color: "#64748b" }}>via your Gmail (from .env)</span>
            </div>
          </div>
        </div>

        {/* AI Generate */}
        <button style={styles.aiBtn} onClick={handleGenerate} disabled={generating}>
          {generating ? "⏳ Generating..." : "🤖 Generate with AI"}
        </button>

        <input
          style={styles.input}
          type="text"
          placeholder="Subject"
          value={subject}
          onChange={(e) => setSubject(e.target.value)}
        />

        <textarea
          style={styles.textarea}
          placeholder="Email body (HTML supported). Use {{TRACKING_LINK}} for clickable link tracking."
          value={body}
          onChange={(e) => setBody(e.target.value)}
        />

        {body && (
          <div style={styles.preview}>
            <p style={styles.previewLbl}>📄 Preview:</p>
            <div dangerouslySetInnerHTML={{ __html: body }} />
          </div>
        )}

        <div style={styles.btnRow}>
          <button style={styles.cancelBtn} onClick={() => navigate("/targets")}>Cancel</button>
          <button style={styles.sendBtn} onClick={handleSend} disabled={sending}>
            {sending ? "Sending..." : `📤 Send as "${showAsName}"`}
          </button>
        </div>
      </div>
    </div>
  );
};

const styles = {
  container: { padding: "2rem", background: "#0f172a", minHeight: "100vh", display: "flex", justifyContent: "center" },
  card: { background: "#1e293b", padding: "2rem", borderRadius: "12px", width: "100%", maxWidth: "720px", height: "fit-content" },
  title: { color: "#f1f5f9", marginBottom: "1rem" },
  targetInfo: { marginBottom: "1rem" },
  badge: { background: "#0f172a", color: "#94a3b8", padding: "0.4rem 0.8rem", borderRadius: "6px", fontSize: "0.85rem" },
  section: { background: "#0f172a", borderRadius: "10px", padding: "1rem", marginBottom: "1rem", border: "1px solid #334155" },
  sectionTitle: { color: "#94a3b8", fontSize: "0.85rem", marginBottom: "0.75rem", fontWeight: "600" },
  presetRow: { display: "flex", flexWrap: "wrap", gap: "0.5rem", marginBottom: "0.75rem" },
  presetBtn: { padding: "0.4rem 0.85rem", background: "#1e293b", border: "1px solid #334155", borderRadius: "20px", color: "#94a3b8", cursor: "pointer", fontSize: "0.8rem" },
  presetBtnActive: { background: "#1e3a5f", borderColor: "#3b82f6", color: "#3b82f6" },
  showAsRow: { display: "flex", gap: "0.75rem", marginBottom: "0.75rem" },
  previewBox: { background: "#1e293b", borderRadius: "8px", padding: "0.75rem", fontSize: "0.82rem" },
  previewRow: { display: "flex", gap: "0.5rem", marginBottom: "0.25rem" },
  previewLabel: { color: "#475569", minWidth: "90px" },
  previewVal: { color: "#10b981" },
  aiBtn: { width: "100%", padding: "0.75rem", background: "#8b5cf6", color: "#fff", border: "none", borderRadius: "8px", cursor: "pointer", fontSize: "1rem", marginBottom: "1rem" },
  input: { width: "100%", padding: "0.75rem", marginBottom: "1rem", borderRadius: "8px", border: "1px solid #334155", background: "#1e293b", color: "#f1f5f9", fontSize: "0.95rem", boxSizing: "border-box" },
  textarea: { width: "100%", padding: "0.75rem", height: "180px", marginBottom: "1rem", borderRadius: "8px", border: "1px solid #334155", background: "#1e293b", color: "#f1f5f9", fontSize: "0.9rem", resize: "vertical", boxSizing: "border-box" },
  preview: { background: "#0f172a", borderRadius: "8px", padding: "1rem", marginBottom: "1rem", color: "#f1f5f9" },
  previewLbl: { color: "#94a3b8", fontSize: "0.85rem", marginBottom: "0.5rem" },
  btnRow: { display: "flex", gap: "1rem" },
  cancelBtn: { flex: 1, padding: "0.75rem", background: "#334155", color: "#f1f5f9", border: "none", borderRadius: "8px", cursor: "pointer" },
  sendBtn: { flex: 1, padding: "0.75rem", background: "#10b981", color: "#fff", border: "none", borderRadius: "8px", cursor: "pointer" },
};

export default ComposeEmailPage;